name: CI
on: [push, pull_request]
env:
  go-version: "1.26.1"
  pg-version: "17"
  postgis-version: "3.5"
  redis-version: "5.0.6"
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgis/postgis:17-3.5
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: temba
          POSTGRES_USER: temba
          POSTGRES_PASSWORD: temba
        options: >-
          --health-cmd "pg_isready -U temba -d temba"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Install Go ${{ env.go-version }}
        run: |
          curl -LO https://go.dev/dl/go${{ env.go-version }}.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go${{ env.go-version }}.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Install Redis
        uses: zhulik/redis-action@v1.0.0
        with:
          redis version: ${{ env.redis-version }}

      - name: Install Linux packages
        run: sudo apt install -y --no-install-recommends postgresql-client

      - name: Initialize database
        # we create our test database with a different user so that we can drop everything owned by this user between tests
        run: |
          export PGPASSWORD=temba
          psql -h localhost -U temba --no-password -c "CREATE USER mailroom_test PASSWORD 'temba';"
          psql -h localhost -U temba --no-password -c "ALTER ROLE mailroom_test WITH SUPERUSER;"
          psql -h localhost -U temba --no-password -c "CREATE DATABASE mailroom_test;"

      - name: Run tests
        run: |
          export PGPASSWORD=temba
          go test -p=1 -coverprofile=coverage.text -covermode=atomic ./...

      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

  release:
    name: Release
    needs: [test]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Fetch GoFlow docs
        # for backward compatibility, English docs are copied to root of docs directory
        run: |
          GOFLOW_VERSION=$(grep goflow go.mod | cut -d" " -f2 | cut -c2-)
          curl -L https://github.com/nyaruka/goflow/releases/download/v${GOFLOW_VERSION}/docs.tar.gz | tar zxv
          cp ./docs/en-us/*.* docs/

      - name: Install Go ${{ env.go-version }}
        run: |
          curl -LO https://go.dev/dl/go${{ env.go-version }}.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go${{ env.go-version }}.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Publish release
        uses: goreleaser/goreleaser-action@v1
        if: ${{ !contains(github.ref, '-') }}
        with:
          version: v0.147.2
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish non-master release
        uses: goreleaser/goreleaser-action@v1
        if: contains(github.ref, '-')
        with:
          version: v0.147.2
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
